rtl8723be-objs :=		\
		dm.o		\
		hw.o		\
		led.o		\
		phy.o		\
		rf.o		\
		sw.o		\
		table.o		\
		trx.o		\
		fw.o		\
		pwrseq.o	\
		pwrseqcmd.o	\
		hal_btc.o	\
	hal_bt_coexist.o	\

obj-$(CONFIG_RTL8723BE) += rtl8723be.o

ccflags-y += -D__CHECK_ENDIAN__ 
